appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EQoj/pKWfPxZWy42AS9iWkHrMvSsPojfN/bVyEOgAL/4QBZTpfwqtW0ShiGWRUs8eukpo1Rs/G+xDSE9Fm9xq1tmbyvDOaVCRZh9orFwwQLmsJIY3lfFS3gH+olPOwIc7xD6k2M7VC+CiIF/R5Lk9y3r6iTnxwuchJEJLleP3OVtXp+s77yOzB5DLuY5q04A3oG3M9z/KUt0QYo0Biy3/9KHl9sXjx30Ps1UXm/SKkWMgkupeKfFmuOgajMalV0L3mY1JpcipLxI9PJlWdDjPdccJvtb+HR7lmfzOKFn3WQxs2fQ41P3QZURxJku2NECkORJS08nHQiMg2FVWoPpX6CEKXC6ITi/KVNwhol7oHc31DZr/d+FQQQ43KbzpzW2lbmErIYXPghapuMF+4qF6qQgeM6LZPKYAmd+YxknHuBcG3GyUEUgt7xq5ln/lKpLj+FWTUobYJYUD10cLN0LLX8gHZZ1SziMW4QYMkTxwv2tXh8/5VFHVU4zrcIcniFqEd1ZvkxIGwy+5/ckkqA2+Nr/axoq/GjIRwakeCDMgrgjMlEeS36HSrBVjiqnVZxk8HMc16YL2queiY1LXtJRJL6rF0J/DGhLCqruO7u3TLTt5f/u4X3Oc5VZYlfyGeRnDZEy84mSDeQ0LTbPEZAd/v2dDHLdTJJAGWcOgXBdhBw=
